### ISSUE TITLE
what your run enviroment？

### ISSUE THREAD

**Issue by freeclouds** [zhangfuyang/rl_CARLA#25]
hi ,i use your python code with python 3.7,tensorflow 1.5.4,carla 0.8.2,ubuntu 18.04
but ,i can't run this simulation,
it work error,
INFO:tensorflow:Restoring parameters from models/saveNet_1907.ckpt-158700
I1106 09:56:56.428069 140117888739136 saver.py:1284] Restoring parameters from models/saveNet_1907.ckpt-158700
Restoring from  models/
start to reset env
Traceback (most recent call last):
  File "/home/robot/work/code/rl/rl_CARLA/environment/carla/client.py", line 174, in _read_sensor_data
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_ddpg.py", line 62, in <module>
    tf.app.run()
  File "/home/robot/.local/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/robot/.local/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/robot/.local/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "test_ddpg.py", line 47, in main
    state = env.reset()
  File "/home/robot/work/code/rl/rl_CARLA/environment/env.py", line 125, in reset
    observation, _, _, _ = self.step(action)
  File "/home/robot/work/code/rl/rl_CARLA/environment/env.py", line 67, in step
    measurements, sensor_data = self.client.read_data()
  File "/home/robot/work/code/rl/rl_CARLA/environment/carla/client.py", line 127, in read_data
    return pb_message, dict(x for x in self._read_sensor_data())
  File "/home/robot/work/code/rl/rl_CARLA/environment/carla/client.py", line 127, in <genexpr>
    return pb_message, dict(x for x in self._read_sensor_data())
RuntimeError: generator raised StopIteration

can you tell me how to deal with this problem？thanks！
or can you tell me your enviroment? thansk!

**Comment by zhangfuyang** [comment]
I guess it's caused by TensorFlow. Can you try using tensorflow 1.12.0? Let me know if it still doesn't work.

**Comment by freeclouds** [comment]
yes ,thansk your suggestion very much,
 i use python 2.7,carla 0.8.2,tensor flow 1.12.0,can run this code.
