### ISSUE TITLE
Client fails to read sensor data from CARLA server.

### ISSUE THREAD

**Issue by CharlesPeng1998** [zhangfuyang/rl_CARLA#32]
After I started CARLA server and ran your python script, I got the following errors:

```
Traceback (most recent call last):
  File "ddpg_main.py", line 149, in <module>
    tf.app.run()
  File "/home/autolab/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "ddpg_main.py", line 140, in main
    agent.train()
  File "/media/autolab/disk_2T/jiancongpeng/repos/rl_CARLA/src/agent/ddpg_agent.py", line 72, in train
    state = self.env.reset()
  File "/media/autolab/disk_2T/jiancongpeng/repos/rl_CARLA/environment/env.py", line 125, in reset
    observation, _, _, _ = self.step(action)
  File "/media/autolab/disk_2T/jiancongpeng/repos/rl_CARLA/environment/env.py", line 67, in step
    measurements, sensor_data = self.client.read_data()
  File "/media/autolab/disk_2T/jiancongpeng/repos/rl_CARLA/environment/carla/client.py", line 127, in read_data
    return pb_message, dict(x for x in self._read_sensor_data())
  File "/media/autolab/disk_2T/jiancongpeng/repos/rl_CARLA/environment/carla/client.py", line 127, in <genexpr>
    return pb_message, dict(x for x in self._read_sensor_data())
RuntimeError: generator raised StopIteration

```

It seemed that the client failed to read sensor data from CARLA server. I am wondering if there is any solution to this problem. Any advice will be helpful to me.

**Comment by zhangfuyang** [comment]
which version of Carla you are using? 0.8.2?

**Comment by CharlesPeng1998** [comment]
Yes. I am using CARLA 0.8.2. But I found the same errors when I ran the example scripts given by CARLA. So I think there is something wrong with my CARLA setup.

**Comment by zhangfuyang** [comment]
I see. Good luck then :)

Let me know if you have other problems. Well, probably I can't give any good advice, since I finished this project 2 years ago and haven't touched the code since then. But I will try my best :D
