### ISSUE TITLE
Use trained model in test _ddpg.py

### ISSUE THREAD

**Issue by lijecaru** [zhangfuyang/rl_CARLA#4]
Hi, you did a great job with this repo. Would you mind explaining how to use the trained DDPG for the test case? Are the new weights saved in the `models` folder after the training is done, or do I have to save them manually using the info in the `results` folder?

**Comment by zhangfuyang** [comment]
Hi. In the training stage, the model (ckpt file) will be stored in result/tf_net directory by default. So you can just copy the file into the 'models/' dir to do testing (as I write in readme). Or you can redirect the model folder for test_ddpg.py script.

**Comment by lijecaru** [comment]
I did as you say several times (changing the path to the stored results and copying the results to the `models/` folder, but I kept getting this error: 
```
Traceback (most recent call last):
  File "test_ddpg.py", line 62, in <module>
    tf.app.run()
  File "/home/user/anaconda3/envs/old-ddpg/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "test_ddpg.py", line 40, in main
    agent = DDPGAgent(sess, action_type, actor, critic, GAMMA, env, Inference=True, Inference_net_dir=FLAGS.model_path)
  File "/home/user/Downloads/rl_CARLA-master/src/agent/ddpg_agent.py", line 26, in __init__
    **env_render=env_render, summary_dir=summary_dir**)
  File "/home/user/Downloads/rl_CARLA-master/src/agent/agent.py", line 40, in __init__
    self.writer = tf.summary.FileWriter(self.summary_dir, sess.graph)
  File "/home/user/anaconda3/envs/old-ddpg/lib/python3.5/site-packages/tensorflow/python/summary/writer/writer.py", line 366, in __init__
    filename_suffix)
  File "/home/user/anaconda3/envs/old-ddpg/lib/python3.5/site-packages/tensorflow/python/summary/writer/event_file_writer.py", line 66, in __init__
    if not gfile.IsDirectory(self._logdir):
  File "/home/user/anaconda3/envs/old-ddpg/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 467, in is_directory
    return pywrap_tensorflow.IsDirectory(compat.as_bytes(dirname), status)
  File "/home/user/anaconda3/envs/old-ddpg/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

```

I found that it keeps asking for these variables `env_render=env_render, summary_dir=summary_dir` that are used in the training file, but not in the test file. Just to test, I added the lines from `ddpg_main.py` that define these variables and then it worked. I am not sure it is the right way though.
